
import { Language } from './types';

export const TRANSLATIONS = {
  vi: {
    appTitle: "AI HR Strategic Director",
    welcome: "Chào mừng CEO chiến lược",
    login: "Đăng nhập/Đăng ký",
    discovery: "Phỏng vấn chiến lược 80/20",
    dashboard: "AI Dashboard Strategic",
    roadmap: "AI Roadmap 10-Steps",
    structure: "AI 80/20 Organization",
    grow: "AI 12-Week GROW Coach",
    power: "AI Power of One Lab",
    thinker: "AI Strategy Lab",
    knowledge: "AI Knowledge & Guide",
    affiliate: "AI Member & Affiliate",
    pdf: "AI Report Export PDF",
    commitment: "AI Digital Commitment",
    reports: "AI Reports & Audit",
    next: "Tiếp theo",
    back: "Quay lại",
    complete: "Hoàn tất chiến dịch",
    done: "Đã thực thi",
    pending: "Chờ triển khai",
    profitGrowth: "Tăng trưởng lợi nhuận 1%",
    progress: "Tiến trình thực thi GROW",
    quickReplies: "Gợi ý trả lời nhanh",
    suggestions: "Gợi ý chiến lược",
    thinkerPrompt: "Nhập vấn đề nhân sự hoặc rào cản tài chính...",
    thinkerAction: "AI đang suy nghĩ sâu (Deep Thinking Mode)...",
    simulation: "Mô phỏng đòn bẩy 1%",
    signPrompt: "Ký tên xác nhận cam kết 12 tuần",
    authSlogan: "12 Tuần kiến tạo lợi nhuận bền vững",
    terminate: "Hủy bỏ phiên làm việc",
    activePhase: "Giai đoạn chiến lược: Hoạt động",
    aiEngineResolved: "AI Engine đã xử lý",
    impact1Percent: "Tác động của thay đổi 1% qua các đòn bẩy",
    baseProfit: "Lợi nhuận gốc",
    forecast12Week: "Dự báo 12 tuần",
    dailyLift: "Tăng trưởng ngày",
    revenueCreators: "Nhóm tạo doanh thu",
    supportOps: "Hỗ trợ / Vận hành",
    backOffice: "Hậu cần / Back-office",
    profitPerEmp: "Lợi nhuận / Nhân sự",
    retentionRoi: "ROI Giữ chân",
    concentration8020: "Tập trung 80/20",
    executionRate: "Tỷ lệ thực thi",
    opexRatio: "Tỷ lệ chi phí vận hành",
    strategicAlignment: "Đồng bộ chiến lược",
    efficiency: "Hiệu quả",
    strategicMindmap: "Sơ đồ tư duy chiến lược",
    reallocateNow: "Tái phân bổ ngay",
    focusTop20: "Tập trung 20% hàng đầu của bạn vào việc tạo ra lợi nhuận.",
    aiDetectedSales: "AI phát hiện đội ngũ Sales của bạn hiện đang thiếu hụt 15% nguồn lực.",
    generateNewAudit: "Tạo kiểm toán mới",
    exportDocDesc: "Xuất các tài liệu chiến lược chất lượng cao do AI tạo ra.",
    customBoardReport: "Cần báo cáo hội đồng quản trị tùy chỉnh?",
    customReportDesc: "Yêu cầu Strategy Lab tạo báo cáo chuyên biệt cho nhà đầu tư hoặc ban quản trị của bạn.",
    openStrategyLab: "Mở AI Strategy Lab",
    charterTitle: "Bản Cam Kết Chiến Lược",
    charterSubtitle: "Mục tiêu tăng trưởng lợi nhuận 1% mỗi ngày",
    disciplineQuote: "Tôi nhận ra rằng sự khác biệt giữa mục tiêu và kết quả là KỶ LUẬT. Tôi cam kết tuân thủ lộ trình 12 tuần để xây dựng một doanh nghiệp vận hành bằng hệ thống.",
    timeCommitment: "Cam kết thời gian",
    timeCommitmentDesc: "Dành ít nhất 5 giờ mỗi tuần cho việc tối ưu hệ thống.",
    actionCommitment: "Cam kết hành động",
    actionCommitmentDesc: "Thực hiện ít nhất 1 thay đổi nhỏ tạo lợi nhuận mỗi ngày.",
    reportingDiscipline: "Kỷ luật báo cáo",
    reportingDisciplineDesc: "Check-in đúng giờ và báo cáo trung thực các chỉ số.",
    signaturePlaceholder: "Nhập tên đầy đủ của bạn",
    signAndBegin: "Ký Cam Kết & Bắt Đầu",
    keyTasks: "Công việc then chốt",
    okrKpi: "Mục tiêu OKR / KPI",
    roadmapDesc: "Lộ trình chiến lược được tạo riêng cho sự phát triển doanh nghiệp của bạn",
    phases: [
      "Giai đoạn 1: Làm rõ mục tiêu & chỉ số",
      "Giai đoạn 2: Tái cấu trúc nhân sự",
      "Giai đoạn 3: Quy trình & kỷ luật",
      "Giai đoạn 4: Tối ưu hiệu suất",
      "Giai đoạn 5: Duy trì & nhân bản"
    ],
    growPhases: {
      G: { label: "Goal", desc: "Mục tiêu tối thượng" },
      R: { label: "Reality", desc: "Hiện trạng thực tế" },
      O: { label: "Options", desc: "Các giải pháp khả thi" },
      W: { label: "Will", desc: "Cam kết hành động" }
    },
    impactHigh: "Tác động cao",
    impactMedium: "Tác động trung bình",
    strategicAdvice: "Lời khuyên chiến lược từ AI",
    focusHrProductivity: "Tập trung vào Năng suất nhân sự để có ROI cao nhất trong tháng này.",
    applyActionPlan: "Áp dụng kế hoạch hành động",
    selectIndustry: "Mô tả lĩnh vực kinh doanh của bạn",
    industryPlaceholder: "Chúng tôi bán gì, cho ai, và giải quyết vấn đề gì?",
    tailoringInterview: "AI đang phân tích mô hình kinh doanh...",
    commonIndustries: ["Bán lẻ (Retail)", "Công nghệ/SaaS", "Sản xuất (Manufacturing)", "F&B/Nhà hàng", "Dịch vụ/Agency", "Thương mại điện tử"],
    deepUnderstanding: "AI đang tìm hiểu chuyên sâu doanh nghiệp của bạn",
    deepUnderstood: "AI đã thấu hiểu hoàn toàn mô hình của bạn",
    startStrategicDeepDive: "Bắt đầu Phân tích Chiến lược 80/20",
    understandingProgress: "Mức độ thấu hiểu của AI",
    aiAnalyzingModel: "AI đang phân tích mô hình kinh doanh..."
  },
  en: {
    appTitle: "AI HR Strategic Director",
    welcome: "Welcome Strategic CEO",
    login: "Login / Register",
    discovery: "80/20 Strategic Interview",
    dashboard: "AI Strategic Dashboard",
    roadmap: "AI 10-Step Roadmap",
    structure: "AI 80/20 Organization",
    grow: "AI 12-Week GROW Coach",
    power: "AI Power of One Lab",
    thinker: "AI Strategy Lab",
    knowledge: "AI Knowledge & Guide",
    affiliate: "AI Member & Affiliate",
    pdf: "AI Report Export PDF",
    commitment: "AI Digital Commitment",
    reports: "AI Reports & Audit",
    next: "Next",
    back: "Back",
    complete: "Complete Campaign",
    done: "Executed",
    pending: "Pending Deployment",
    profitGrowth: "1% Profit Growth",
    progress: "GROW Execution Progress",
    quickReplies: "Quick Replies",
    suggestions: "Strategic Suggestions",
    thinkerPrompt: "Enter HR issue or financial bottleneck...",
    thinkerAction: "AI is deep thinking (Deep Thinking Mode)...",
    simulation: "1% Leverage Simulation",
    signPrompt: "Sign to confirm 12-week commitment",
    authSlogan: "12 Weeks to Sustainable Profitability",
    terminate: "Terminate Session",
    activePhase: "Strategic Phase: Active",
    aiEngineResolved: "AI Engine Resolved",
    impact1Percent: "Impact of 1% change across key levers",
    baseProfit: "Base Profit",
    forecast12Week: "12-Week Forecast",
    dailyLift: "Daily Lift",
    revenueCreators: "Revenue Creators",
    supportOps: "Support / Ops",
    backOffice: "Back-office",
    profitPerEmp: "Profit / Employee",
    retentionRoi: "Retention ROI",
    concentration8020: "80/20 Concentration",
    executionRate: "Execution Rate",
    opexRatio: "Opex Ratio",
    strategicAlignment: "Strategic Alignment",
    efficiency: "Efficiency",
    strategicMindmap: "Strategic Mindmap",
    reallocateNow: "Re-allocate Now",
    focusTop20: "Focus your top 20% on profit generation.",
    aiDetectedSales: "AI detected that your Sales team is currently under-resourced by 15%.",
    generateNewAudit: "Generate New Audit",
    exportDocDesc: "Export high-fidelity strategic documents generated by AI.",
    customBoardReport: "Need a Custom Board Report?",
    customReportDesc: "Ask the Strategic Lab to generate a specialized report for your investors or management board.",
    openStrategyLab: "Open AI Strategy Lab",
    charterTitle: "Strategic Commitment Charter",
    charterSubtitle: "1% Daily Profit Growth Target",
    disciplineQuote: "I recognize that the difference between a goal and a result is DISCIPLINE. I commit to following the 12-week roadmap to build a systems-driven business.",
    timeCommitment: "Time Commitment",
    timeCommitmentDesc: "Dedicate at least 5 hours per week to system optimization.",
    actionCommitment: "Action Commitment",
    actionCommitmentDesc: "Implement at least 1 small profit-generating change daily.",
    reportingDiscipline: "Reporting Discipline",
    reportingDisciplineDesc: "Check-in on time and report metrics honestly.",
    signaturePlaceholder: "Enter your full name",
    signAndBegin: "Sign & Begin Execution",
    keyTasks: "Key Tasks",
    okrKpi: "OKR / KPI",
    roadmapDesc: "Strategic roadmap generated specifically for your business growth",
    phases: [
      "Phase 1: Clear Goals & Metrics",
      "Phase 2: HR Restructuring",
      "Phase 3: Processes & Discipline",
      "Phase 4: Performance Optimization",
      "Phase 5: Maintenance & Scaling"
    ],
    growPhases: {
      G: { label: "Goal", desc: "Ultimate Objective" },
      R: { label: "Reality", desc: "Current Status" },
      O: { label: "Options", desc: "Viable Solutions" },
      W: { label: "Will", desc: "Will to Execute" }
    },
    impactHigh: "High Impact",
    impactMedium: "Medium Impact",
    strategicAdvice: "AI Strategic Advice",
    focusHrProductivity: "Focus on HR Productivity for the highest ROI this month.",
    applyActionPlan: "Apply Action Plan",
    selectIndustry: "Describe your business field",
    industryPlaceholder: "What do we sell, to whom, and why?",
    tailoringInterview: "AI is analyzing your business model...",
    commonIndustries: ["Retail", "Technology/SaaS", "Manufacturing", "F&B/Restaurant", "Service/Agency", "E-commerce"],
    deepUnderstanding: "AI is deeply learning about your business",
    deepUnderstood: "AI has fully understood your model",
    startStrategicDeepDive: "Start 80/20 Strategic Deep-Dive",
    understandingProgress: "AI Understanding Level",
    aiAnalyzingModel: "AI is analyzing business model..."
  }
};

export const AI_SUGGESTIONS = {
  vi: [
    "Làm thế nào để áp dụng quy luật 80/20 vào quản trị nhân sự?",
    "Chiến lược Power of One giúp tăng 1% lợi nhuận mỗi ngày như thế nào?",
    "Cách tái cấu trúc đội ngũ để tập trung vào nhóm tạo doanh thu?",
    "Làm sao để duy trì kỷ luật trong lộ trình 12 tuần GROW?",
    "Làm thế nào để đo lường ROI của việc giữ chân nhân tài?"
  ],
  en: [
    "How to apply the 80/20 rule to HR management?",
    "How does the Power of One strategy increase profit by 1% daily?",
    "How to restructure the team to focus on revenue generators?",
    "How to maintain discipline during the 12-week GROW roadmap?",
    "How to measure the ROI of talent retention?"
  ]
};
